### ISSUE TITLE
How to use??

### ISSUE THREAD

**Issue by mediaistic** [sulmanpucit/Fusion-Builder-Alternative-Colors#1]
Firstly - well done on creating this - it could be very popular!!

I installed the plugin and activated.
It seems to have changed the colour of the boxes to blue.
I figured it must be a little customisable, so looked at the PHP, and realised there were 'skins' there, with different colour schemes. However I can't find any way of activating a skin, and other than 'activating' there doesn't seem to be any instructions in the documentation.

Or have I got it wrong - and it just changes the boxes blue?

**Comment by sulmanpucit** [comment]
It actually follows admin color schemes. Which you can change from your profile. 

![a](https://cloud.githubusercontent.com/assets/934675/20229740/ed58a55a-a879-11e6-902d-30186f565491.png)

Here is a screenshot of available color schemes.
![a](https://cloud.githubusercontent.com/assets/934675/20229765/1213a20a-a87a-11e6-80ac-27056e692b6a.png)

Hope it helps :)
